.default_tag: &default_tag
  tags:
    - backend-docker-large

image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

stages:
  - build
  - deploy

compile:
  stage: build
  <<: *default_tag
  when: manual
  script:
    - mvn -U compile
  only:
    - merge_requests
    - web
  except:
    - master

deploy_artifacts:
  stage: deploy
  <<: *default_tag
  when: manual
  allow_failure: true
  script:
    - mvn clean deploy -U -DskipTests
  only:
    - merge_requests
    - web
  except:
    - master
    - develop